theme: jekyll-theme-dinky
name: PyQrack
title: PyQrack
url: https://pyqrack.github.io

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
